# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'search_keywords.ui'
#
# Created: Sun Aug 26 11:46:33 2018
#      by: pyside2-uic  running on PySide2 5.11.0a1.dev1525359714
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(666, 805)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem, 5, 0, 1, 1)
        self.line_edit_json_file = QtWidgets.QLineEdit(Form)
        self.line_edit_json_file.setObjectName("line_edit_json_file")
        self.gridLayout_2.addWidget(self.line_edit_json_file, 4, 2, 1, 1)
        self.line_edit_html_file = QtWidgets.QLineEdit(Form)
        self.line_edit_html_file.setObjectName("line_edit_html_file")
        self.gridLayout_2.addWidget(self.line_edit_html_file, 6, 2, 1, 1)
        self.button_html_browser = QtWidgets.QPushButton(Form)
        self.button_html_browser.setObjectName("button_html_browser")
        self.gridLayout_2.addWidget(self.button_html_browser, 8, 3, 1, 1)
        self.radio_html = QtWidgets.QRadioButton(Form)
        self.radio_html.setObjectName("radio_html")
        self.gridLayout_2.addWidget(self.radio_html, 6, 0, 1, 1)
        self.label_json_file = QtWidgets.QLabel(Form)
        self.label_json_file.setObjectName("label_json_file")
        self.gridLayout_2.addWidget(self.label_json_file, 4, 1, 1, 1)
        self.line_edit_html_template = QtWidgets.QLineEdit(Form)
        self.line_edit_html_template.setObjectName("line_edit_html_template")
        self.gridLayout_2.addWidget(self.line_edit_html_template, 7, 2, 1, 1)
        self.label_html_template = QtWidgets.QLabel(Form)
        self.label_html_template.setObjectName("label_html_template")
        self.gridLayout_2.addWidget(self.label_html_template, 7, 1, 1, 1)
        self.label_html_browser = QtWidgets.QLabel(Form)
        self.label_html_browser.setObjectName("label_html_browser")
        self.gridLayout_2.addWidget(self.label_html_browser, 8, 1, 1, 1)
        self.radio_stdout = QtWidgets.QRadioButton(Form)
        self.radio_stdout.setChecked(True)
        self.radio_stdout.setObjectName("radio_stdout")
        self.gridLayout_2.addWidget(self.radio_stdout, 2, 0, 1, 1)
        self.label_html_file = QtWidgets.QLabel(Form)
        self.label_html_file.setObjectName("label_html_file")
        self.gridLayout_2.addWidget(self.label_html_file, 6, 1, 1, 1)
        self.line_edit_html_browser = QtWidgets.QLineEdit(Form)
        self.line_edit_html_browser.setObjectName("line_edit_html_browser")
        self.gridLayout_2.addWidget(self.line_edit_html_browser, 8, 2, 1, 1)
        self.button_json_file = QtWidgets.QPushButton(Form)
        self.button_json_file.setObjectName("button_json_file")
        self.gridLayout_2.addWidget(self.button_json_file, 4, 3, 1, 1)
        self.button_html_file = QtWidgets.QPushButton(Form)
        self.button_html_file.setObjectName("button_html_file")
        self.gridLayout_2.addWidget(self.button_html_file, 6, 3, 1, 1)
        self.radio_json = QtWidgets.QRadioButton(Form)
        self.radio_json.setObjectName("radio_json")
        self.gridLayout_2.addWidget(self.radio_json, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem1, 3, 0, 1, 1)
        self.button_html_template = QtWidgets.QPushButton(Form)
        self.button_html_template.setObjectName("button_html_template")
        self.gridLayout_2.addWidget(self.button_html_template, 7, 3, 1, 1)
        self.check_box_insensitive = QtWidgets.QCheckBox(Form)
        self.check_box_insensitive.setChecked(True)
        self.check_box_insensitive.setObjectName("check_box_insensitive")
        self.gridLayout_2.addWidget(self.check_box_insensitive, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem2, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 4, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.button_help = QtWidgets.QPushButton(Form)
        self.button_help.setObjectName("button_help")
        self.horizontalLayout_8.addWidget(self.button_help)
        self.button_default = QtWidgets.QPushButton(Form)
        self.button_default.setObjectName("button_default")
        self.horizontalLayout_8.addWidget(self.button_default)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem3)
        self.button_execute = QtWidgets.QPushButton(Form)
        self.button_execute.setObjectName("button_execute")
        self.horizontalLayout_8.addWidget(self.button_execute)
        self.gridLayout.addLayout(self.horizontalLayout_8, 7, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.group_box_directories = QtWidgets.QGroupBox(Form)
        self.group_box_directories.setObjectName("group_box_directories")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.group_box_directories)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.list_view_directories = QtWidgets.QListView(self.group_box_directories)
        self.list_view_directories.setObjectName("list_view_directories")
        self.gridLayout_3.addWidget(self.list_view_directories, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.group_box_directories)
        self.group_box_keywords = QtWidgets.QGroupBox(Form)
        self.group_box_keywords.setObjectName("group_box_keywords")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.group_box_keywords)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.list_view_keywords = QtWidgets.QListView(self.group_box_keywords)
        self.list_view_keywords.setObjectName("list_view_keywords")
        self.gridLayout_4.addWidget(self.list_view_keywords, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.group_box_keywords)
        self.group_box_ignores = QtWidgets.QGroupBox(Form)
        self.group_box_ignores.setObjectName("group_box_ignores")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.group_box_ignores)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.list_view_ignores = QtWidgets.QListView(self.group_box_ignores)
        self.list_view_ignores.setObjectName("list_view_ignores")
        self.gridLayout_5.addWidget(self.list_view_ignores, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.group_box_ignores)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 1, 0, 1, 1)
        self.text_edit_result = QtWidgets.QTextEdit(Form)
        self.text_edit_result.setReadOnly(True)
        self.text_edit_result.setObjectName("text_edit_result")
        self.gridLayout.addWidget(self.text_edit_result, 5, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_config = QtWidgets.QLabel(Form)
        self.label_config.setObjectName("label_config")
        self.horizontalLayout.addWidget(self.label_config)
        self.line_edit_config = QtWidgets.QLineEdit(Form)
        self.line_edit_config.setObjectName("line_edit_config")
        self.horizontalLayout.addWidget(self.line_edit_config)
        self.button_config = QtWidgets.QPushButton(Form)
        self.button_config.setObjectName("button_config")
        self.horizontalLayout.addWidget(self.button_config)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 6, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtWidgets.QApplication.translate("Form", "Form", None, -1))
        self.button_html_browser.setText(QtWidgets.QApplication.translate("Form", "Browse", None, -1))
        self.radio_html.setText(QtWidgets.QApplication.translate("Form", "HTML", None, -1))
        self.label_json_file.setText(QtWidgets.QApplication.translate("Form", "File", None, -1))
        self.label_html_template.setText(QtWidgets.QApplication.translate("Form", "Template", None, -1))
        self.label_html_browser.setText(QtWidgets.QApplication.translate("Form", "Browser", None, -1))
        self.radio_stdout.setText(QtWidgets.QApplication.translate("Form", "Standard Out", None, -1))
        self.label_html_file.setText(QtWidgets.QApplication.translate("Form", "File", None, -1))
        self.button_json_file.setText(QtWidgets.QApplication.translate("Form", "Browse", None, -1))
        self.button_html_file.setText(QtWidgets.QApplication.translate("Form", "Browse", None, -1))
        self.radio_json.setText(QtWidgets.QApplication.translate("Form", "JSON", None, -1))
        self.button_html_template.setText(QtWidgets.QApplication.translate("Form", "Browse", None, -1))
        self.check_box_insensitive.setText(QtWidgets.QApplication.translate("Form", "Insensitive", None, -1))
        self.button_help.setText(QtWidgets.QApplication.translate("Form", "Help", None, -1))
        self.button_default.setText(QtWidgets.QApplication.translate("Form", "Default", None, -1))
        self.button_execute.setText(QtWidgets.QApplication.translate("Form", "Execute", None, -1))
        self.group_box_directories.setTitle(QtWidgets.QApplication.translate("Form", "Directories", None, -1))
        self.group_box_keywords.setTitle(QtWidgets.QApplication.translate("Form", "Keywords", None, -1))
        self.group_box_ignores.setTitle(QtWidgets.QApplication.translate("Form", "Ignores", None, -1))
        self.label_config.setText(QtWidgets.QApplication.translate("Form", "Config File", None, -1))
        self.button_config.setText(QtWidgets.QApplication.translate("Form", "Open", None, -1))

